# Generated by Django 4.1.7 on 2023-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=15, verbose_name='название')),
                ('opisanie', models.CharField(default='', max_length=40, verbose_name='название')),
                ('image_tov', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='otz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=15, verbose_name='название')),
                ('opisanie', models.CharField(default='', max_length=40, verbose_name='название')),
                ('image_tov', models.ImageField(upload_to='')),
            ],
        ),
    ]
