# Generated by Django 4.1.7 on 2023-04-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoroselProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=25, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=150, verbose_name='Описание')),
                ('image', models.ImageField(max_length=500, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение')),
                ('price', models.CharField(default='', max_length=20, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='CoroselReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=25, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=150, verbose_name='Описание')),
                ('image', models.ImageField(max_length=500, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
